Package the app up as a fat JAR with Dependencies built in
This makes it much easier to build, test and run on the command line.
This also simplifies the build process and stops us having dependencies
written into the setup file and the pom.xml file.

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -64,74 +64,6 @@ fail() {
   exit 1
 }
 
-download_jar() {
-  group_id=$1
-  artifact_id=$2
-  version=$3
-  prefix="http://search.maven.org/remotecontent?filepath="
-  path=${group_id//.//}
-  jar_name=$artifact_id-$version.jar
-  tmp_dest=$(mktemp -u)
-  jar_dest=$dependencies_dir/$jar_name
-  url=${prefix}${path}/${artifact_id}/${version}/${jar_name}
-  
-  # file exists? then don't download it!
-  [[ -f ${jar_dest} ]] && return
-
-  # download the file to a temp location, then if move it here if successful
-  echo "Downloading $jar_name ($url)..."
-  wget -q -P ${dependencies_dir} $url -O ${tmp_dest} && \
-    mv ${tmp_dest} ${jar_dest}
-
-  # Purge our temp file regardless of the status here
-  rm -f ${tmp_dest}
-}
-
-download_dependencies() {
-  which ant > /dev/null || $install_package ant
-  which wget > /dev/null || $install_package wget
-  
-  install -d ${dependencies_dir}
-  
-  echo "Downloading dependencies ..."
-  aws_java_sdk_version="1.11.28"
-  
-  remote_mvn_pkg="com.amazonaws:aws-java-sdk-core:${aws_java_sdk_version} \
-                  com.amazonaws:aws-java-sdk-kinesis:${aws_java_sdk_version} \
-                  com.amazonaws:aws-java-sdk-cloudwatch:${aws_java_sdk_version} \
-                  com.amazonaws:aws-java-sdk-sts:${aws_java_sdk_version} \
-                  com.amazonaws:aws-java-sdk-ec2:${aws_java_sdk_version} \
-                  com.fasterxml.jackson.core:jackson-annotations:2.6.3 \
-                  com.fasterxml.jackson.core:jackson-core:2.6.3 \
-                  com.fasterxml.jackson.core:jackson-databind:2.6.3 \
-                  com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:2.6.3 \
-                  com.google.code.findbugs:jsr305:3.0.1 \
-                  com.google.guava:guava:18.0 \
-                  org.apache.httpcomponents:httpclient:4.5.1 \
-                  org.apache.httpcomponents:httpclient-cache:4.5.1 \
-                  org.apache.httpcomponents:httpmime:4.5.1 \
-                  org.apache.httpcomponents:httpcore:4.4.3 \
-                  org.apache.httpcomponents:httpcore-ab:4.4.3 \
-                  org.apache.httpcomponents:httpcore-nio:4.4.3 \
-                  commons-cli:commons-cli:1.2 \
-                  commons-codec:commons-codec:1.6 \
-                  commons-logging:commons-logging-adapters:1.1 \
-                  commons-logging:commons-logging-api:1.1 \
-                  org.apache.commons:commons-lang3:3.4 \
-                  log4j:log4j:1.2.17 \
-                  org.slf4j:slf4j-api:1.7.12 \
-                  org.slf4j:slf4j-log4j12:1.7.12 \
-                  com.beust:jcommander:1.48 \
-                  org.xerial:sqlite-jdbc:3.8.11.2 \
-                  joda-time:joda-time:2.8.2 \
-                  org.projectlombok:lombok:1.16.6"
-  
-  for package in ${remote_mvn_pkg}
-  do
-   download_jar $(echo $package | tr : " ")
-  done
-}
-
 do_uninstall () {
   echo "Uninstalling $daemon_name ..."
   # stop the service if it's running
@@ -169,9 +101,7 @@ do_uninstall () {
 }
 
 do_build () {
-  download_dependencies
-  
-  ant || fail "Failed to build the Java project"
+  mvn package || fail "Failed to build the Java project"
 }
 
 do_install () {
@@ -196,7 +126,7 @@ do_install () {
   install -m755 ./bin/${daemon_name}.${dist} ${init_dir}/${daemon_name}
   install -m644 ./support/${daemon_name}.cron ${cron_dir}/${daemon_name}
   install -m644 ./support/${daemon_name}.sysconfig ${sysconfig_dir}/${daemon_name}
-  install -m644 ./support/log4j.xml ${config_dir}
+  install -m644 ./src/main/resources/log4j.xml ${config_dir}
 
   # add a user for starting the agent
   id -u $agent_user_name > /dev/null 2>&1 || \
